name = "Landed"
license = "Creative Commons Attribution 3.0"
licenselink = "https://github.com/MarcusVirg/forty/blob/master/LICENSE.md"
description = "A portfolio/blog website built for companies or personal freelancers."
homepage = "//github.com/yoshikawaa/landed"
tags = ["portfolio", "company", "contact form", "google analytics", "blog"]
features = ["blog"]
min_version = "0.29"

[author]
  name = "Atsushi Yoshikawa"
  homepage = "https://io.github.yoshikawaa"

# If porting an existing theme
[original]
  author = "AJ"
  name = "HTML5 Up"
  homepage = "https://html5up.net/landed"